//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Retreat_Management_System
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdminAction
    {
        public int AdminActionID { get; set; }
        public Nullable<int> AdminID { get; set; }
        public string ActionType { get; set; }
        public string TargetEntity { get; set; }
        public Nullable<System.DateTime> ActionDate { get; set; }
        public string Description { get; set; }
    
        public virtual User User { get; set; }
    }
}
