//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Retreat_Management_System
{
    using System;
    using System.Collections.Generic;
    
    public partial class Organizer
    {
        public Organizer()
        {
            this.Retreats = new HashSet<Retreat>();
        }
    
        public int OrganizerID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Email { get; set; }
        public string PhoneNumber { get; set; }
        public string CompanyName { get; set; }
        public string ContactInfo { get; set; }
        public Nullable<int> UserID { get; set; }
    
        public virtual User User { get; set; }
        public virtual ICollection<Retreat> Retreats { get; set; }
    }
}
