//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Retreat_Management_System
{
    using System;
    using System.Collections.Generic;
    
    public partial class Retreat
    {
        public Retreat()
        {
            this.Bookings = new HashSet<Booking>();
            this.Feedbacks = new HashSet<Feedback>();
        }
    
        public int RetreatID { get; set; }
        public string RetreatName { get; set; }
        public string Description { get; set; }
        public string Location { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public decimal Price { get; set; }
        public int Capacity { get; set; }
        public string ImageURL { get; set; }
        public string ContactInfo { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<int> OrganizerID { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<System.DateTime> LastUpdated { get; set; }
        public string Status { get; set; }
    
        public virtual ICollection<Booking> Bookings { get; set; }
        public virtual ICollection<Feedback> Feedbacks { get; set; }
        public virtual Organizer Organizer { get; set; }
        public virtual User User { get; set; }
    }
}
